<?php

function translate_month( $month )
{
    $months = array( "Jan" => "Январь", "Feb" => "Февраль", "Mar" => "Март", "Apr" => "Апрель", "May" => "Май", "Jun" => "Июнь", " Jul " => "Июль ", "Aug" => "Август", "Sep" => "Сентябрь", "Oct" => "Октябрь", "Nov" => "Ноябрь", "Dec" => "Декабрь" );
    if ( isset( $months[$month] ) )
    {
        $month = $months[$month];
    }
    return $month;
}

function lang_interior_color( $color )
{
    $array = array( "GRY" => "Серый", "SILVER" => "Серебристый", "SLV" => "Серебристый", "MAROON" => "Красный", "BLACK" => "Черный", "BLUE" => "Светло синий", "BLU" => "Синий", "GOLD" => "Золотой", "BEI" => "Бежевый", "BEIGE" => "Бежевый", "CHAMP" => "Шампанское", "BRN" => "Коричневый", "TAN" => "Бежевый", "GRAY" => "Серый", "GREEN" => "Зеленый", "WHITE" => "Белый", "RED" => "Красный", "BLK" => "Черный", "BROWN" => "Коричневый", "OLIVE" => "Оливковый" );
    if ( isset( $array[$color] ) )
    {
        $color = $array[$color];
    }
    return $color;
}

function lang_interior_type( $type )
{
    $array = array( );
    $array['Cloth'] = "Ткань/материал";
    $array['Leather'] = "Кожа";
    $array['Other'] = "Другое";
    $array['Vinyl'] = "Винил";
    if ( isset( $array[$type] ) )
    {
        $type = $array[$type];
    }
    return $type;
}

function translate_time_left( $days = null, $hours = null, $minutes = null )
{
    $days_lang = array( );
    $days_lang[0] = "день";
    $days_lang[1] = "дня";
    $days_lang[2] = "дней";
    $hours_lang = array( );
    $hours_lang[0] = "час";
    $hours_lang[1] = "часа";
    $hours_lang[2] = "часов";
    $minutes_lang = array( );
    $minutes_lang[0] = "минута";
    $minutes_lang[1] = "минуты";
    $minutes_lang[2] = "минут";
    $time_left = "";
    if ( empty( $days ) )
    {
        $days_last = substr( $days, -1, 1 );
        if ( $days != 11 && $days_last == 1 )
        {
            $days_string = $days_lang[0];
        }
        else
        {
            if ( ( !( 11 < $days ) || !( $days < 15 ) ) && 1 < $days_last && $days_last < 5 )
            {
                $days_string = $days_lang[1];
            }
            else
            {
                $days_string = $days_lang[2];
            }
        }
        if ( $days )
        {
            $time_left .= $days." ".$days_string." ";
        }
    }
    if ( empty( $hours ) )
    {
        $hours_last = substr( $hours, -1, 1 );
        if ( $hours != 11 && $hours_last == 1 )
        {
            $hours_string = $hours_lang[0];
        }
        else if ( ( !( 11 < $hours ) || !( $hours < 15 ) ) && 1 < $hours_last && $hours_last < 5 )
        {
            $hours_string = $hours_lang[1];
        }
        else
        {
            $hours_string = $hours_lang[2];
        }
        $time_left .= $hours." ".$hours_string." ";
    }
    if ( empty( $minutes ) )
    {
        $minutes_last = substr( $minutes, -1, 1 );
        if ( $minutes != 11 && $minutes_last == 1 )
        {
            $minutes_string = $minutes_lang[0];
        }
        else if ( ( !( 11 < $minutes ) || !( $minutes < 15 ) ) && 1 < $minutes_last && $minutes_last < 5 )
        {
            $minutes_string = $minutes_lang[1];
        }
        else
        {
            $minutes_string = $minutes_lang[2];
        }
        $time_left .= $minutes." ".$minutes_string." ";
    }
    return $time_left;
}

$lang_colors = array( );
$lang_colors['Beige'] = "Бежевый";
$lang_colors['Black'] = "Черный";
$lang_colors['Blue'] = "Синий";
$lang_colors['Brown'] = "Коричневый";
$lang_colors['Burgundy'] = "Красный";
$lang_colors['Charcoal'] = "Угольно серый";
$lang_colors['Copper'] = "Медно-красный";
$lang_colors['Gold'] = "Золотой";
$lang_colors['Gray'] = "Серый";
$lang_colors['Green'] = "Зеленый";
$lang_colors['Off White'] = "Белый";
$lang_colors['Orange'] = "Оранжевый";
$lang_colors['Purple'] = "Фиолетовый";
$lang_colors['Red'] = "Красный";
$lang_colors['Silver'] = "Серебристый";
$lang_colors['Tan'] = "желто-коричневый";
$lang_colors['White'] = "Белый";
$lang_colors['Yellow'] = "Желтый";

$lang_colors['BEIGE'] = "Бежевый";
$lang_colors['BLACK'] = "Черный";
$lang_colors['BLUE'] = "Синий";
$lang_colors['BROWN'] = "Коричневый";
$lang_colors['BURGUNDY'] = "Красный";
$lang_colors['CHARCOAL'] = "Угольно серый";
$lang_colors['COPPER'] = "Медно-красный";
$lang_colors['GOLD'] = "Золотой";
$lang_colors['GRAY'] = "Серый";
$lang_colors['GREEN'] = "Зеленый";
$lang_colors['OFF WHITE'] = "Белый";
$lang_colors['ORANGE'] = "Оранжевый";
$lang_colors['PURPLE'] = "Фиолетовый";
$lang_colors['RED'] = "Красный";
$lang_colors['SILVER'] = "Серебристый";
$lang_colors['TAN'] = "желто-коричневый";
$lang_colors['WHITE'] = "Белый";
$lang_colors['YELLOW'] = "Желтый";

$lang_colors['Not Available'] = "Нет информации";
$lang_colors['Other'] = "Неизвестно";
$lang_refinement = array( );
$lang_refinement['Sale Location'] = "Место продажи";
$lang_refinement['Region'] = "Регион";
$lang_refinement['State or Province'] = "Штат или провинция";
$lang_refinement['Vehicle Type'] = "Тип транспорта";
$lang_refinement['Make'] = "Марка";
$lang_refinement['Model'] = "Модель";
$lang_refinement['Body Style'] = "Тип кузова";
$lang_refinement['Year'] = "Год";
$lang_refinement['Trim'] = "Модификация";
$lang_refinement['Auction Sale Date Range'] = "Дата продажи";
$lang_refinement['Auction Sale Date'] = "Дата продажи (дни)";
$lang_refinement['Mileage'] = "Пробег (мили)";
$lang_refinement['Year Range'] = "Года";
$lang_refinement['MMR Price Range'] = "Прогнозируемая цена";
$lang_refinement['Inventory Source'] = "Продавец";
$lang_refinement['Engine Size'] = "Объем двигателя";
$lang_refinement['Fuel Type'] = "Тип топлива";
$lang_refinement['Transmission'] = "КПП";
$lang_refinement['Top Type'] = "Тип крыши";
$lang_refinement['Doors'] = "К-во дверей";
$lang_refinement['Exterior Color'] = "Цвет";
$lang_refinement['Interior Type'] = "Тип салона";
$lang_refinement_sub = array( );
$array = array( );
$array['Cloth'] = "Ткань";
$array['Leather'] = "Кожа";
$array['Other'] = "Другое";
$array['Vinyl'] = "Винил";
$lang_refinement_sub['Interior Type'] = $array;
$array = array( );
$array['Beige'] = "Бежевый";
$array['Black'] = "Черный";
$array['Blue'] = "Синий";
$array['Brown'] = "Коричневый";
$array['Burgundy'] = "Красный";
$array['Charcoal'] = "Угольно-серый";
$array['Copper'] = "Медно-красный";
$array['Gold'] = "Золотой";
$array['Gray'] = "Серый";
$array['Green'] = "Зеленый";
$array['Off White'] = "Белый";
$array['Orange'] = "Оранжевый";
$array['Purple'] = "Фиолетовый";
$array['Red'] = "Красный";
$array['Silver'] = "Серебро";
$array['Tan'] = "Бежевый";
$array['White'] = "Белый";
$array['Yellow'] = "Желтый";
$array['Not Available'] = "Нет информации";
$array['Other'] = "Другой";
$lang_refinement_sub['Exterior Color'] = $array;
$array = array( );
$array['Convertible Top'] = "Откидной верх";
$array['Hard Top Roof'] = "Жесткая крыша";
$array['Moon Roof'] = "Прозрачный люк";
$array['Sun Roof'] = "Обычный люк";
$array['T-Top Roof'] = "T-образная";
$array['Tilt Slide Roof'] = "Панарамный люк";
$array['Vinyl Top Roof'] = "Виниловый верх";
$lang_refinement_sub['Top Type'] = $array;
$array = array( );
$array['Automatic'] = "Автоматическая";
$array['Manual'] = "Механическая";
$array['Other'] = "Другая";
$array['Unknown'] = "Неизвестно";
$lang_refinement_sub['Transmission'] = $array;
$array = array( );
$array['Diesel'] = "Дизель";
$array['Ethanol'] = "Этанол";
$array['Gasoline'] = "Бензин";
$array['Hybrid'] = "Гибрид";
$array['Propane'] = "Пропан";
$lang_refinement_sub['Fuel Type'] = $array;
$array = array( );
$array['1 Cylinder'] = "1 цилиндр";
$array['2 Cylinder'] = "2 цилиндра";
$array['3 Cylinder'] = "3 цилиндра";
$array['4 Cylinder'] = "4 цилиндра";
$array['5 Cylinder'] = "5 цилиндров";
$array['6 Cylinder'] = "6 цилиндров";
$array['8 Cylinder'] = "8 цилиндров";
$array['10 Cylinder'] = "10 цилиндров";
$array['12 Cylinder'] = "12 цилиндров";
$lang_refinement_sub['Engine Size'] = $array;
$array = array( );
$array[] = array( "pattern" => "#([$\\d,]+) to ([$\\d,]+)#", "replace" => "От \\1 до \\2" );
$array[] = array( "pattern" => "#([$\\d,]+) and higher#", "replace" => "От \\1 и больше" );
$lang_refinement_sub['MMR Price Range']['dynamic'] = $array;
$array = array( );
$array[] = array( "pattern" => "#(\\d{4}) - Newer#", "replace" => "От \\1 и новее" );
$array[] = array( "pattern" => "#(\\d{4}) and Older#", "replace" => "От \\1 и старше" );
$lang_refinement_sub['Year Range']['dynamic'] = $array;
$array = array( );
$array[] = array( "pattern" => "#Under ([\\d,]+)#", "replace" => "Менее \\1 миль" );
$array[] = array( "pattern" => "#More than ([\\d,]+) miles#", "replace" => "Более \\1 миль" );
$lang_refinement_sub['Mileage']['dynamic'] = $array;
$array = array( );
$array[] = array( "pattern" => "#(\\w{3}) (\\d{2}), (\\d{4})#e", "replace" => "translate_month(\\1).\" \\2, \\3\"" );
$lang_refinement_sub['Auction Sale Date']['dynamic'] = $array;
$array = array( );
$array['Today'] = "Сегодня";
$array['This Week (Sun-Sat)'] = "На этой неделе";
$array['Next Week'] = "На следующей неделе";
$array['This Month'] = "В этом месяце";
$array['Next Month'] = "В следующем месяце";
$lang_refinement_sub['Auction Sale Date Range'] = $array;
$array = array( );
$array['Car'] = "Легковой";
$array['SUV'] = "Внедорожник";
$array['Truck'] = "Грузовик / пикап";
$array['Van'] = "Минивэн";
$array['Boat'] = "Лодка";
$array['Motorcycle'] = "Мотоцикл";
$array['Recreational'] = "Для путешествий";
$array['Other'] = "Другое";

$lang_refinement_sub['Vehicle Type'] = $array;

$array = array( );

$array['Canada'] = 'Канада';
$array['Mid West'] = "Средний Запад";
$array['North East'] = "Северный Восток";
$array['South East'] = "Южный Восток";
$array['South West'] = "Южный Запад";
$array['West'] = "Запад";
$lang_refinement_sub['Region'] = $array;
$lang = array( );
$lang['list']['colors'] = $lang_colors;
$lang['list']['refinement'] = $lang_refinement;
$lang['list']['refinement_sub'] = $lang_refinement_sub;
$array = array( );
$array['BEIGE'] = "Бежевый";
$array['BLACK'] = "Черный";
$array['BLUE'] = "Синий";
$array['BROWN'] = "Коричневый";
$array['BURGANDY'] = "Красный";
$array['BURGUNDY'] = "Красный";
$array['CHARCOAL'] = "Угольно-серый";
$array['COPPER'] = "Медно-красный";
$array['GOLD'] = "Золотой";
$array['GRAY'] = "Серый";
$array['GREEN'] = "Зеленый";
$array['OFF WHITE'] = "Белый";
$array['ORANGE'] = "Оранжевый";
$array['ORANG'] = "Оранжевый";
$array['PURPLE'] = "Фиолетовый";
$array['RED'] = "Красный";
$array['SILVER'] = "Серебро";
$array['TAN'] = "Бежевый";
$array['WHITE'] = "Белый";
$array['YELLOW'] = "Желтный";
$array['N/A'] = "Неизвестно";
$array['DK GREEN'] = "Темно-зеленый";
$array['SLATE'] = "Синевато-серый";
$array['BRONZE'] = "Бронзовый";
$array['GSY'] = "GSY";
$array['GRY'] = "Серый";
$array['BEI'] = "Бежевый";
$array['SIL'] = "Серебро";
$array['GREY'] = "Серый";
$array['TEAL'] = "Синий";
$array['Green'] = "Зеленый";
$array['UNAVAILABLE'] = "НЕДОСТУПНО";
$array['WHT 040'] = "Белый";
$array['STRAT'] = "Синий";
$array['SLIVER'] = "Серебро";
$array['BGE'] = "Бежевый";
$array['GRA'] = "Серый";
$array['WHT'] = "Белый";
$array['CRM'] = "CRM";
$array['BRN'] = "Каричневый";
$array['LNMST'] = "Серебро";
$array['SLVR'] = "Серебро";
$array['WHI'] = "Белый";
$array['CHAMPGNE'] = "Бежевая";
$array['MDGREEN'] = "Темно-зеленый";
$array['MAROON'] = "Темно-красный";
$array['TEALMET'] = "Синий";
$array['SEP.BRNZ'] = "Коричневый";
$array['BLKSAPPH'] = "Черный";
$array['BLACK SA'] = "Черный";
$array['CARBNBLK'] = "Черный";
$array['DK/ BLU'] = "Темно-синий";
$array['TTANM'] = "Серебро";
$array['NONE'] = "Неизвестно";
$array['UNAVAIL'] = "Неизвестно";
$array['DESERT SAND MICA'] = "Бежевый";
$array['SUPER WHITE'] = "Белый";
$array['BLK'] = "Черный";
$array['WHI 040'] = "Белый";
$array['RED 3R3'] = "Красный";
$array['RED/3Q3'] = "Красный";
$array['BISQUE'] = "Серый";
$array['SIL/'] = "Серебро";
$array['SILVER FROST'] = "Серебро";
$array['RED/'] = "Красный";
$array['BARC RED'] = "Красный";
$array['WHT/040'] = "Белый";
$array['LT/BLUE'] = "Светло-синий";
$array['BLK/'] = "Черный";
$array['GRN/'] = "Зеленый";
$array['SLV\x01D4'] = "Серебро";
$array['SLV'] = "Серебро";
$array['AQUA'] = "Синий";
$array['GRE'] = "Серый";
$array['WHT/'] = "Белый";
$array['LTBLUE'] = "Светло-синий";
$array['LT BLUE'] = "Светло-синий";
$array['BLU/'] = "Синий";
$array['SIL 1D4'] = "Серебро";
$array['BBLUE'] = "Синий";
$array['BLK 202'] = "Черный";
$array['SALSA RD'] = "Красный";
$array['LTBLU'] = "Светло-синий";
$array['GLD 4Q2'] = "Золото";
$array['RED 3Q3'] = "Красный";
$array['BLU 8S4'] = "Синий";
$array['GRY 1E3'] = "Серый";
$array['SIL 1CB'] = "Серебро";
$array['TITANIUM'] = "Серебро";
$array['SLVR/1D4'] = "Серебро";
$array['BLUE SIL'] = "Серебро";
$array['GRY 1C8'] = "Серый";
$array['GRAPHITE'] = "Серый";
$array['TAN 4Q2'] = "Бежевый";
$array['TAN/4Q2'] = "Бежевый";
$array['BIEGE'] = "Бежевый";
$array['DSSND'] = "Бежевый";
$array['GREY/1E3'] = "Серый";
$array['PHANTOM'] = "Серый";
$array['GR'] = "Серый";
$array['LTGRAY'] = "Светло-серый";
$array['DKBLUE'] = "Темно-синий";
$array['BURG'] = "Темно-красный";
$array['CHARC BG'] = "Темно-серый";
$array['DKGREY'] = "Темно-серый";
$array['BLCKSAPH'] = "Черный";
$array['019'] = "Черный";
$array['LT.BLUE'] = "Светло-синий";
$array['VIOLET'] = "Фиолетовый";
$array['VIOLET'] = "Фиолетовый";
$array['TAN/WHIT'] = "Белый";
$array['WHON'] = "Белый";
$array['SILVERST'] = "Серебро";
$array['CRM'] = "Светло-желтый";
$array['OTHER'] = "Другое";
$lang['list']['colors'] = $array;
$array = array( );
$array['first'] = "начало";
$array['<<first'] = "<<начало";
$array['previous'] = "назад";
$array['<previous'] = "<назад";
$array['next'] = "вперед";
$array['next>'] = "вперед>";
$array['last'] = "конец";
$array['last>>'] = "конец>>";
$lang['list']['nav'] = $array;
$array = array( );
$array['Air Conditioning'] = "Кондиционер";
$array['Cruise Control'] = "Круиз-контроль";
$array['Power Locks'] = "Центральный замок";
$array['Power Mirrors'] = "Электрорегулировка зеркал";
$array['Alloy Wheels'] = "Легкосплавные диски";
$array['Power Seats'] = "Элетрорегулировка сидений";
$array['Power Steering'] = "Усилитель рулевого управления";
$array['Power Windows'] = "Электрические стеклоподъемники";
$array['Rear Defroster'] = "Обогреватель заднего стекла";
$array['Tilt Steering'] = "Регулировка наклона рулевой колонки";
$array['Tinted Glass'] = "Тонированные стекла";
$array['Climate Control'] = "Климат контроль";
$array['Rear Air Conditioning'] = "Задний кондиционер";
$array['Wheels - Alloy'] = "Литые диски";
$array['Satellite Radio'] = "Спутниковое радио";
$array['CD Changer'] = "CD-чейнджер";
$array['On-Board Computer'] = "Бортовой компьютер";
$array['Not Available'] = "Нет данных";
$array['Wheels - Steel'] = 'Колеса - стальные';
$array['Bumper - Chrome'] = 'Бампер - хромированный';
$array['Bumper - Plastic'] = 'Бампер - пластиковый';
$array['Dual Rear Wheels'] = 'Двойные задние колеса';
$array['Mudflaps'] = 'Брызговики';
$array['Wheel Covers'] = 'Колпаки';
$array[''] = '';
$array[''] = '';
$array[''] = '';
$array[''] = '';
 $array['АС'] = "Кондиционер";
 $array['Television'] = "Телевизор";
 $array['dual sliding side'] = "Сдвижная дверь";
 $array['Cassette Tape'] = "Кассетный магнитофон";
 $array['Single Sliding  Door'] = "Одна сдвижная дверь";
 $array['Adjustable Pedals'] = "Регулируемые педали";
 $array['Power Vent Windows'] = "Электр. форточки";
 $array['Woodgrain Interior Package'] = "Вставки под дерево";
 $array['Warranty Books'] = "Гарантийные книги";
 $array['Vinyl'] = "Винил";
 $array['Two-Wheel Drive'] = "Привод на два колеса";
 $array['Trip Counter'] = "Счетчик пробега";
 $array['Trailer Hitch'] = "Прицепное устройство";
 $array['Traction Control'] = "Контроль тягового усилия";
 $array['Tire Pressure Monitor'] = "Датчик давления в шинах";
 $array['Tire Inflator'] = "Насос для накачивания шин";
 $array['Tinted Windows'] = "Тонированные стекла";
 $array['Tilt Steering'] = "Регулировка наклона рулевой колонки";
 $array['Third Seat'] = "3-й ряд сидений";
 $array['Telescopic Steering Wheel'] = "Продольная регулировка рулевой колонки";
 $array['Tape/CD'] = "Кассета/CD";
 $array['Sun Roof'] = "Люк";
 $array['Sun Roof'] = "Люк";
 $array['Steering Wheel Audio Control'] = "Мультируль - управление аудио на руле";
 $array['Side Air Bags'] = "Боковые аэрбеги";
 $array['Security System'] = "Сигнализация";
 $array['Ride control'] = "Контроль  плавности хода";
 $array['Rear Wiper'] = "Дворник заднего стекла";
 $array['Rear Defrost'] = "Обогреватель заднего стекла";
 $array['Rear Air Conditioning'] = "Задний кондиционер";
 $array['Rain Sensor'] = "Датчик дождя";
 $array['Pwr Window'] = "Стекла с электроприводом";
 $array['Pwr Steering'] = "Гидроусилитель руля";
 $array['Pwr Seats'] = "Электропривод сидений";
 $array['Pwr Lock'] = "Электрозамки";
 $array['Pwr Glass Sun Roof'] = "Люк прозрачный с электроприводом";
 $array['Power Mirrors'] = "Зеркала с электроприводом";
 $array['Power Lift Gate'] = "Электропривод задней  двери";
 $array['Parking Distance Control'] = "Парктроник";
 $array['Owner&#039;s Manual'] = "Руководство по эксплуатации";
 $array['Navigation System'] = "Навигация";
 $array['Memory Seat'] = "Память регулировки сидений";
 $array['Luggage Rack'] = "Полка багажника";
 $array['HomeLink'] = "Дистанционное открывание ворот";
 $array['Heated Seats'] = "Подогрев сидений";
 $array['Heated Mirrors'] = "Обогрев зеркал";
 $array['Fog Lamps'] = "Противотуманные фары";
 $array['Floor Mats'] = "Коврики";
 $array['First Aid Kit'] = "Медицинская аптечка";
 $array['Dual Air Conditioning'] = "Раздельный кондиционер";
 $array['Dual Air Bags'] = "Два передних аэрбега";
 $array['Directional Stability Control'] = "Контроль курсовой устойчивости";
 $array['Cruise Ctl'] = "Круиз-контроль";
 $array['CD Player'] = "CD плеер";
 $array['ABS Brakes'] = "ABS тормозов";
 $array['A/C'] = "Кондиционер";
 $array['7 Passenger Seating'] = "7 местный";
 $array['7 Door'] = "7 дверный";
 $array['6 Door'] = "6 дверный";
 $array['5 Passenger Seating'] = "5 местный";
 $array['5 Door'] = "5 дверный";
 $array['4 Door'] = "4 дверный";
 $array['3 Door'] = "3 дверный";
 $array['Maintenance Records'] = "Сервисная книга";
 $array['Wheel Locks'] = "Секретки на колесах";
 $array['Keyless Entry'] = "Управление замками с брелка";
 $array['NO Rear Air Conditioning'] = "Нет заднего кондиционера";
 $array['NO Third Seat'] = "Нет 3-го ряда сидений";
 $array['2 Air Bags'] = "2 аэрбега";
 $array['Xenon Headlights'] = "Ксеноновые фары";
 $array['Power Folding Mirrors'] = "Электрически складывающиеся зеркала";
 $array['Cargo Net'] = "Сеточка для груза";
 $array['Trip Computer'] = "Маршрутный компьютер";
 $array['Power Lift Gate'] = "Электрозамок  задней  двери";
 $array['Power Trunk/Liftgate'] = "Электрозамок  задней  двери";
 $array['Pwr Seats - Drivers Only'] = "Электропривод сидений - только водителя";
 $array['Pwr Seats - Both'] = "Электропривод сидений - оба";
 $array['Power Tilt Steering'] = "Электрическая регулировка наклона рулевой колонки";
 $array['Premium Stereo - DSP'] = "Хорошая стереосистема с DSP";
// $array['On-Board Computer'] = "On-Board Computer";
// $array['Sunshade - Power'] = "Sunshade - Power";
// $array['Cooled Seats'] = "Cooled Seats";
// $array['Heads Up Display'] = "Heads Up Display";
// $array['Power Telescopic Steering'] = "Power Telescopic Steering";
 $array['AM/FM Radio'] = "AM/FM радио";
// $array['Single Air Bags'] = "Single Air Bags";
// $array['Trailering Package'] = "Trailering Package";
// $array['On-Star'] = "On-Star";
// $array['US EPA Label'] = "US EPA Label";
// $array['Fleet Side'] = "Fleet Side";
 $array['Short Bed'] = "Малая кровать";
// $array['Rear Tail/Lift Gate'] = "Rear Tail/Lift Gate";
 $array['MP3 compatible'] = "Поддерживает MP3";
// $array['Running Board'] = "Running Board";
 $array['Sliding Rear Glass'] = "Сдвигающееся заднее стекло";
// $array['Turn Signal Mirrors'] = "Turn Signal Mirrors";
 $array['Spoiler'] = "Спойлер";
 $array['Heated Rear Seats'] = "Подогрев задних сидений";
 //$array['California Emissions'] = "California Emissions";
// $array['Hand Tool Kit'] = "Hand Tool Kit";
 //$array['Sunshade - Manual'] = "Sunshade - Manual";
// $array['Auto-Suspension'] = "Auto-Suspension";
 $array['Cell Phone - OEM'] = "Сотовый телефон - OEM";
 $array['Rear View Camera'] = "Камера заднего вида";



$lang['Options'] = $array;
$array = array( );
$array['Received at Auction'] = "Получен на аукционе";
$array['Not Available'] = "Нет данных";
$array['Clean'] = "Чистый";
$lang['Title Status'] = $array;

$array = array( );
$array['Cyl. Gasoline Turbo'] = "цил. турбо бензин" ;
$array['Cyl. Gasoline'] = "цил. бензин" ;
$array['Cyl. Diesel'] = "цил. турбо-дизель" ;
$array['Cyl. Diesel'] = "цил. дизель" ;
$array['Cyl. Ethanol'] = " цил. этинол" ;
$array['Cyl. Hybrid'] = "цил. гибрид" ;
$array['Cyl. Gasoline'] = "цил. бензин";
$lang['simple engine'] = $array;


$array = array( );
$array['Car'] = "Легковой автомобиль";
$array['SUV'] = "Внедорожник";
$array['Truck'] = "Пикап";
$array['Van'] = "Фургон";
$array['Boat'] = "Лодка";
$array['Motorcycle'] = "Мотоцикл";
$array['Recreational'] = "Развлекательный";
$array['Other'] = "Другое";
$array['Not Available'] = "Нет данных";
$lang['Vehicle Type'] = $array;
$array = array( );
$array['Not Available'] = "Нет данных";
$array['Other'] = "Другой";
$array['NONE'] = "Нет";
$lang['available'] = $array;
$array = array( );
$array['Not Available'] = "Нет данных";
$array['Other'] = "Другой";
$array['NONE'] = "Нет";
$array['Dual'] = "Две";
$array['Yes'] = "Есть";
$lang['Airbags'] = $array;
$array = array( );
$array['Yes'] = "Да";
$array['No'] = "Нет";
$array['Unknown'] = "Неизвестно";
$lang['yes_no'] = $array;
$array = array( );
$array['Convertible Top'] = "Откидной верх";
$array['Hard Top Roof'] = "Жесткая крыша";
$array['Moon Roof'] = "Прозрачный люк";
$array['Sun Roof'] = "Обычный люк";
$array['T-Top Roof'] = "T-образная";
$array['Tilt Slide Roof'] = "Панарамный люк";
$array['Vinyl Top Roof'] = "Пластиковый верх";
$array['Not Available'] = "Нет данных";
$lang['Top Type'] = $array;
$array = array( );
$array['CD Player'] = "CD-плеер";
$array['AM Radio'] = "Радио";
$array['Cassette Tape'] = "Кассетный магнитофон";
$array['Not Available'] = "Нет информации";
$lang['Stereo'] = $array;
$array = array( );
$array['Cloth'] = "Ткань";
$array['Leather'] = "Кожа";
$array['Other'] = "Другое";
$array['Vinyl'] = "Винил";
$array['Not Available'] = "Нет данных";
$lang['Interior Type'] = $array;




$array = array( );
$array['Lift Gate'] = "Подъемная задняя дверь";
$array['Trim Panel'] = "Внутренняя обшивка";
$array['Center Cap'] = "Крышка на литые диски";
$array['Deck Lid'] = "Крышка багажника";
$array['Trunk Floor/Tir'] = "Ниша запасного колеса";
$array['Wheel Housin'] = "Чашка";
$array['Rear View Mirror'] = "Зеркало заднего вида";
$array['Wheel Cover'] = "Колпак";

$array['Overall Vehicle'] = "Вся машина";
$array['Overall Picture'] = "Общее фото";
$array['Ovrall Picture'] = "Общее фото";
$array['Vinyl'] = "Винил";
$array['Vinyl'] = "Винил";
$array['Vinyl'] = "Винил";





$lang['damage_table_1'] = $array;

$array = array( );
$array['Beige'] = "Бежевый";
$array['Black'] = "Черный";
$array['Blue'] = "Синий";
$array['Brown'] = "Коричневый";
$array['Burgundy'] = "Темно-красный";
$array['Charcoal'] = "Темно-серый";
$array['Copper'] = "Медно-красный";
$array['Gold'] = "Золото";
$array['Gray'] = "Серый";
$array['Grey'] = "Серый";
$array['Green'] = "Зеленый";
$array['Off White'] = "Оттенок белого";
$array['Orange'] = "Оранжевый";
$array['Purple'] = "Фиолетовый";
$array['Red'] = "Красный";
$array['Silver'] = "Серебро";
$array['Tan'] = "Бежевый";
$array['White'] = "Белый";
$array['Yellow'] = "Желтый";
$array['Not Available'] = "Нет данных";
$array['Other'] = "Неизвестно";
$lang['Colors'] = $array;
$array = array( );
$array['Diesel'] = "Дизель";
$array['Ethanol'] = "Этанол";
$array['Gasoline'] = "Бензин";
$array['Hybrid'] = "Гибрид";
$array['Propane'] = "Пропан";
$array['Not Available'] = "Нет данных";
$lang['Fuel Type'] = $array;
$array = array( );
$array['Automatic'] = "Автоматическая";
$array['Manual'] = "Ручная";
$array['Other'] = "Другая";
$array['Unknown'] = "Неизвестно";
$array['Not Available'] = "Нет данных";
$lang['Transmission'] = $array;
$array = array( );
$array['All Wheel Drive'] = "Привод на все колёса";
$array['Other'] = "Другая";
$array['Unknown'] = "Неизвестно";
$array['Not Available'] = "Нет данных";
$lang['Drive Train'] = $array;
$array = array( );
$array['1 Cylinder'] = "1 цилиндр";
$array['2 Cylinder'] = "2 цилиндра";
$array['3 Cylinder'] = "3 цилиндра";
$array['4 Cylinder'] = "4 цилиндра";
$array['5 Cylinder'] = "5 цилиндров";
$array['6 Cylinder'] = "6 цилиндров";
$array['8 Cylinder'] = "8 цилиндров";
$array['10 Cylinder'] = "10 цилиндров";
$array['12 Cylinder'] = "12 цилиндров";
$array['Not Available'] = "Не доступно";
$lang['Engine Size'] = $array;
$array = array( );
$array['Convertible'] = "Купе";
$array['Coupe'] = "Купе";
$array['Extended Cab'] = "Купе";
$array['MPV'] = "Купе";
$array['RegularCab'] = "Купе";
$array['Sedan'] = "Седан";
$array['Wagon'] = "Универсал";
$array['SUV'] = "Внедорожник";
$array['Truck'] = "Пикап";
$array['Not Available'] = "Не доступно";
$lang['Body Style'] = $array;
$array = array( );
$array['Overall Picture - Front'] = "Cпереди";
$array['Overall Picture - Rear'] = "Cзади";
$array['Overall Picture - Engine'] = "Двигатель";
$array['Overall Picture - Interior'] = "Cалон";
$array['Overall Picture - Odometer'] = "Cпидометр";
$array['Overall Picture - Wheel'] = "Колесо";
$array['Overall Picture - Dash'] = "Приборная панель";
$array['Overall Picture - Left'] = "Cлева";
$array['Overall Picture - Right'] = "Cпава";
$array['Front Bumper'] = "Передний бампер";
$array['Rear Bumper'] = "Задний бампер";
$array['Hood'] = "Капот";
$array['Roof'] = "Крыша";
$array['Deck Lid'] = "Крышка багажника";
$array['LF Fender'] = "Левое переднее крыло";
$array['RF Fender'] = "Правое переднее крыло";
$array['LR Fender'] = "Левое заднее крыло";
$array['RR Fender'] = "Правое заднее крыло";
$array['LF Mirror Housing'] = "Левое зеркало";
$array['RR Door'] = "Правая задняя двер";
$array['LR Door'] = "Левая задняя двер";
$array['RF Door'] = "Правая передняя дверь";
$array['LF Door'] = "Левая передняя дверь";
$array['Windshield'] = "Ветровое стекло";
$array['R Qtr Panel'] = "Правое крыло";
$array['L Qtr Panel'] = "Левое крыло";
$array['R Bed Side'] = "Правая задняя сторона";
$array['L Bed Side'] = "Левая задняя сторона";
$array['Tailgate'] = "Задний откидной борт ";
$array['Warning - Airbag'] = "Подушка безопасности";
$array['NONE'] = "";
$lang['thumbs']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#Picture \\#(\\d+)#", "replace" => "Фото \\1" );
$lang['thumbs']['dynamic'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^(\d+) Cylinder Gas#", "replace" => "$1-цилиндровый бензин" );
$array[] = array( "pattern" => "#^(\d+) Cylinder Gas Turbo#", "replace" => "$1-цилиндровый бензин турбо" );
$array[] = array( "pattern" => "#(\d+) Cylinder Diesel#", "replace" => "$1-цилиндровый дизель" );
$array[] = array( "pattern" => "#^(\d+) Cylinder Diesel Turbo#", "replace" => "$1-цилиндровый дизель турбо" );
$array[] = array( "pattern" => "#(\d+) Cylinder Ethanol#", "replace" => "\\1-цилиндровый этанол" );
$array[] = array( "pattern" => "#(\d+) Cylinder Hybrid#", "replace" => "\\1-цилиндровый гибрид" );
$array[] = array( "pattern" => "#(\d+) Propane#", "replace" => "\\1 пропан" );
$array[] = array( "pattern" => "#(\d+) Speed#", "replace" => "\\1 ступенчатая КПП" );
$array[] = array( "pattern" => "#^([\d.]+) L#", "replace" => "\\1 л." );
$lang['report']['mechanical']['dynamic'] = $array;
$array = array( );
$array['Automatic'] = "Автоматическая КПП";
$array['AWD (Cars)'] = "Полный привод (Cars)";
$array['Pwr Brakes'] = "Усилитель тормозов";
$array['4X2 (Trucks/SUVs)'] = "4X2 (Trucks/SUVs)";
$array['S'] = "S";
$lang['report']['mechanical']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#Fuel Level: ([\\d/]+)#", "replace" => "Уровень топлива: \\1" );
$lang['report']['fluid_levels']['dynamic'] = $array;
$array = array( );
$array['Fuel Level: Full'] = "Уровень топлива: полный";
$array['Fuel Level: Unknown'] = "Уровень топлива: неизвестно";
$array['Fuel Level: Empty'] = "Уровень топлива: пусто";
$lang['report']['fluid_levels']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^LF -#", "replace" => "Лев/пер -" );
$array[] = array( "pattern" => "#^RF -#", "replace" => "Прав/пер -" );
$array[] = array( "pattern" => "#^LR -#", "replace" => "Лев/зад -" );
$array[] = array( "pattern" => "#^RR -#", "replace" => "Прав/зад -" );
$array[] = array( "pattern" => "#^SP -#", "replace" => "Запаска -" );
$array[] = array( "pattern" => "#^Tire Condition:#", "replace" => "Состояние резины:" );
$lang['report']['tires_and_weels']['dynamic'] = $array;
$array = array( );
$array['Tire Condition: Average'] = "Состояние резины: среднее";
$array['Tire Condition: Good'] = "Состояние резины: хорошее";
$array['Tire Condition: Poor'] = "Состояние резины: изношена";
$array['Tire Condition: New'] = "Состояние резины: новая";
$array['Wheels - Alloy'] = "Легкосплавные диски";
$array['All Wheel Steering'] = "All Wheel Steering";
$array['Wheels - Steel'] = "Стальные диски";
$array['Wheels - Chrome'] = "Хромированные диски";
$array['Wheels - Sport'] = "Спортивные диски";
$lang['report']['tires_and_weels']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^LF -#", "replace" => "Лев/пер -" );
$array[] = array( "pattern" => "#^RF -#", "replace" => "Прав/пер -" );
$array[] = array( "pattern" => "#^LR -#", "replace" => "Лев/зад -" );
$array[] = array( "pattern" => "#^RR -#", "replace" => "Прав/зад -" );
$array[] = array( "pattern" => "#^SP -#", "replace" => "Запаска -" );
$array[] = array( "pattern" => "#^([A-Z]{2,6}) - (\\w+)#e", "replace" => "lang_interior_color('\\1').' - '.lang_interior_type('\\2')" );
$array[] = array( "pattern" => "#^Odometer - (\\d+) Digits Digital - Operable#", "replace" => "Спидометр - цифровой (\\1 цифр) - работает" );
$array[] = array( "pattern" => "#^Odometer - (\\d+) Digits Analog - Operable#", "replace" => "Спидометр - аналоговый (\\1 цифр) - работает" );
$array[] = array( "pattern" => "#^Int Odor:#", "replace" => "Запах в салоне:" );
$lang['report']['interior']['dynamic'] = $array;
$array = array( );
$array['Foul'] = "Грязный";
$array['Dirty'] = "Грязный";
$array['Average'] = "Среднее";
$array['Clean'] = "Чистый";
$array['Stained'] = "Запачканный";
$array['Int Odor: OK'] = "Запах в салоне: ok";
$array['Wood Trim Dash'] = "Приборная панель &quot;под дерево&quot;";
$array['Woodgrain Interior Package'] = "Вставки &quot;под дерево&quot;";
$array['Regular Dash'] = "Стандартная приборная панель";
$lang['report']['interior']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^Master Key -#", "replace" => "Главный ключ -" );
$array[] = array( "pattern" => "#^Remote Key/Fob -#", "replace" => "Пульт/брелок -" );
$array[] = array( "pattern" => "#^Infrared Key -#", "replace" => "Чип-ключ -" );
$array[] = array( "pattern" => "#^Spare Key -#", "replace" => "Запасной ключ -" );
$array[] = array( "pattern" => "#^Valet Key -#", "replace" => "Дверной ключ -" );
$array[] = array( "pattern" => "#^Combo Key -#", "replace" => "Ключ с пультом -" );
$array[] = array( "pattern" => "#^Keyless Entry#", "replace" => "Управление замками с брелка" );
$lang['report']['keys']['dynamic'] = $array;
$array = array( "АС" => "Кондиционер", "Television" => "Телевизор", "dual sliding side" => "Сдвижная дверь", "Cassette Tape" => "Кассетный магнитофон", "Single Sliding  Door" => "Одна сдвижная дверь", "Adjustable Pedals" => "Регулируемые педали", "Power Vent Windows" => "Электр. форточки", "Woodgrain Interior Package" => "Вставки под дерево", "Warranty Books" => "Гарантийные книги", "Vinyl" => "Винил", "Two-Wheel Drive" => "Привод на два колеса", "Trip Counter" => "Счетчик пробега", "Trailer Hitch" => "Прицепное устройство", "Traction Control" => "Контроль тягового усилия", "Tire Pressure Monitor" => "Датчик давления в шинах", "Tire Inflator" => "Насос для накачивания шин", "Tinted Windows" => "Тонированные стекла", "Tilt Steering" => "Регулировка наклона рулевой колонки", "Third Seat" => "3-й ряд сидений", "Telescopic Steering Wheel" => "Продольная регулировка рулевой колонки", "Tape/CD" => "Кассета/CD", "Sun Roof" => "Люк", "Sun Roof" => "Люк", "Steering Wheel Audio Control" => "Мультируль - управление аудио на руле", "Side Air Bags" => "Боковые аэрбеги", "Security System" => "Сигнализация", "Ride control" => "Контроль  плавности хода", "Rear Wiper" => "Дворник заднего стекла", "Rear Defrost" => "Обогреватель заднего стекла", "Rear Air Conditioning" => "Задний кондиционер", "Rain Sensor" => "Датчик дождя", "Pwr Window" => "Стекла с электроприводом", "Pwr Steering" => "Гидроусилитель руля", "Pwr Seats" => "Электропривод сидений", "Pwr Lock" => "Электрозамки", "Pwr Glass Sun Roof" => "Люк прозрачный с электроприводом", "Power Mirrors" => "Зеркала с электроприводом", "Power Lift Gate" => "Электропривод задней  двери", "Parking Distance Control" => "Парктроник", "Owner&#039;s Manual" => "Руководство по эксплуатации", "Navigation System" => "Навигация", "Memory Seat" => "Память регулировки сидений", "Luggage Rack" => "Полка багажника", "HomeLink" => "Дистанционное открывание ворот", "Heated Seats" => "Подогрев сидений", "Heated Mirrors" => "Обогрев зеркал", "Fog Lamps" => "Противотуманные фары", "Floor Mats" => "Коврики", "First Aid Kit" => "Медицинская аптечка", "Dual Air Conditioning" => "Раздельный кондиционер", "Dual Air Bags" => "Два передних аэрбега", "Directional Stability Control" => "Контроль курсовой устойчивости", "Cruise Ctl" => "Круиз-контроль", "CD Player" => "CD плеер", "ABS Brakes" => "ABS тормозов", "A/C" => "Кондиционер", "7 Passenger Seating" => "7 местный", "7 Door" => "7 дверный", "6 Door" => "6 дверный", "5 Passenger Seating" => "5 местный", "5 Door" => "5 дверный", "4 Door" => "4 дверный", "3 Door" => "3 дверный", "Maintenance Records" => "Сервисная книга", "Wheel Locks" => "Секретки на колесах", "Keyless Entry" => "Управление замками с брелка", "NO Rear Air Conditioning" => "Нет заднего кондиционера", "NO Third Seat" => "Нет 3-го ряда сидений", "2 Air Bags" => "2 аэрбега", "Xenon Headlights" => "Ксеноновые фары", "Power Folding Mirrors" => "Электрически складывающиеся зеркала", "Cargo Net" => "Сеточка для груза", "Trip Computer" => "Маршрутный компьютер", "Power Lift Gate" => "Электрозамок  задней  двери", "Power Trunk/Liftgate" => "Электрозамок  задней  двери", "Pwr Seats - Drivers Only" => "Электропривод сидений - только водителя", "Pwr Seats - Both" => "Электропривод сидений - оба", "Power Tilt Steering" => "Электрическая регулировка наклона рулевой колонки", "Premium Stereo - DSP" => "Premium Stereo - DSP", "On-Board Computer" => "On-Board Computer", "Sunshade - Power" => "Sunshade - Power", "Cooled Seats" => "Cooled Seats", "Heads Up Display" => "Heads Up Display", "Power Telescopic Steering" => "Power Telescopic Steering", "AM/FM Radio" => "AM/FM радио", "Single Air Bags" => "Single Air Bags", "Trailering Package" => "Trailering Package", "On-Star" => "On-Star", "US EPA Label" => "US EPA Label", "Fleet Side" => "Fleet Side", "Short Bed" => "Short Bed", "Rear Tail/Lift Gate" => "Rear Tail/Lift Gate", "MP3 compatible" => "MP3 compatible", "Running Board" => "Running Board", "Sliding Rear Glass" => "Sliding Rear Glass", "Turn Signal Mirrors" => "Turn Signal Mirrors", "Spoiler" => "Spoiler", "Heated Rear Seats" => "Heated Rear Seats", "California Emissions" => "California Emissions", "Hand Tool Kit" => "Hand Tool Kit", "Sunshade - Manual" => "Sunshade - Manual", "Auto-Suspension" => "Auto-Suspension", "Cell Phone - OEM" => "Cell Phone - OEM", "Rear View Camera" => "Rear View Camera", "111111" => "111111", "111111" => "111111", "111111" => "111111", "111111" => "111111", "111111" => "111111", "111111" => "111111" );
$lang['report']['options']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^CD Changer - OEM#", "replace" => "CD чейнджер - OEM" );
$array[] = array( "pattern" => "#^CD Changer - FACTORY#", "replace" => "CD чейнджер - FACTORY" );
$array[] = array( "pattern" => "#^Satellite Radio -#", "replace" => "Satellite Radio -" );
$array[] = array( "pattern" => "#^Premium Stereo -#", "replace" => "Premium Stereo -" );
$lang['report']['options']['dynamic'] = $array;
$array = array( "ANNOUNCED CONDITION" => "Заявленное состояние", "INTERNET REMARKS" => "Интернет замечания", "REMARKS/ADDITIONAL DAMAGE" => "Замечания/дополнительные повреждения", "DISCLOSURES" => "Официальная информация", "NOTES TO CONSIGNOR" => "Замечания для получателя", "REMARKS" => "Замечания", "COMMENTS FOR CONSIGNOR" => "Комментарии для получателя" );
$lang['report']['conditions']['key'] = $array;
$array = array( "Lift Gate" => "Подъемная задняя дверь", "Trim Panel" => "Внутренняя обшивка", "Center Cap" => "Крышка на литые диски", "Deck Lid" => "Крышка багажника", "Trunk Floor/Tir" => "Ниша запасного колеса", "Wheel Housin" => "Чашка", "Rear View Mirror" => "Зеркало заднего вида", "Wheel Cover" => "Колпак", "Mirror Housi" => "Наружные зеркала", "Oil" => "Масло", "Rail/Unirail" => "Лонжероны", "Unibody" => "Кузов", "Headlights" => "Фара", "Edge" => "Край", "Headlight" => "Фара", "Multiple" => "Много", "dual sliding side" => "Сдвижная дверь", "R Qtr Panel" => "Правая зад/бок панель", "L Qtr Panel" => "Левая зад/бок панель", "АС" => "Кондиционер", "Wheels - Steel" => "Диски - стальные", "Wheels - Alloy" => "Диски - литые", "Multiple Chips" => "Cколы", "Air Conditioner" => "Возд. кондиционер", "Single Sliding  Door" => "Одна сдвижная дверь", "Front Bumper" => "Передний бампер", "Rear Bumper" => "Задний бампер", "LF Fender" => "Лев/пер крыло", "RF Fender" => "Прав/пер крыло", "LR Fender" => "Левое/зад крыло", "RR Fender" => "Прав/зад крыло", "LF Door" => "Лев/пер дверь", "RF Door" => "Прав/пер дверь", "LR Door" => "Левое/зад дверь", "RR Door" => "Прав/зад дверь", "Struc. Damage" => "Повреждение несущей части", "Headliner" => "Обшивка потолка", "Rear Cover Refl" => "Задний отражатель", "Rear Body Panel" => "Задняя панель", "Left Side" => "Левая сторона", "Fog Light" => "Противотуманная фара", "Filler" => "Заглушка", "Noise" => "Звук", "Rear End/Differ" => "Задний дифференциал (раздатка)", "Turn Signal" => "Поворотный сигнал", "Warning" => "Осторожно!", "Idle" => "Холостой ход", "Windshield" => "Лобовое стекло", "Interior" => "Салон", "Window" => "Окно", "Bumper" => "Бампер", "Hood" => "Капот", "Fender" => "Крыло", "Tire" => "Покрышка", "Molding" => "Молдинг", "Door" => "Дверь", "Panel" => "Панель", "Qtr" => "Бок", "Rocker Panel" => "Порог", "Tail" => "Задняя", "Lamp" => "Фара", "Seat" => "Сиденье", "Cushion" => "Подушка", "Core Support" => "Рамка радиатора", "Engine" => "Двигатель", "Hoses" => "Шланги", "Belts" => "Ремни", "Pillar" => "Стойка", "Apron" => "Брызговик лонжерона", "Stained" => "В пятнах", "Brakes" => "Тормоза", "Roof" => "Крыша", "Spare" => "Запасн.", "Both" => "Оба", "Flare" => "Накладка арки", "Wheel" => "Покрышка", "Peeling" => "Ободрана", "Chips" => "Cколы", "Headrest" => "Подголовник", "Rear" => "Сзади", "Front" => "Спереди", "Carpet" => "Ковер", "Overall Picture" => "Фото","Overall Vehicle" => "Вся машина" );
$lang['report']['damages']['description']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^\\s*Picture \\#(\\d+)#", "replace" => "Фото \\1 " );
$lang['report']['damages']['description']['dynamic'] = $array;
$array = array( "Inop" => "Не работает", "Multiple Chips" => "Множественные сколы", "Stained" => "Пятна", "Surface Damage" => "Повреждение поверхности", "Substd Repair" => "Не очень качественный ремонт", "Mult Scratches" => "Множественные царапины", "Scratches" => "Царапины", "On Car" => "В машине", "Edge" => "Сколы", "Light Damage" => "Легкое повреждение", "Peeling" => "Ободр.", "Burn" => "Прожженная", "Scratch" => "Царапина", "Dents" => "Вмятины", "Dent/No Paint Dmg" => "Вмятина/Не закрашенное повреждение", "Dings" => "Маленькие вмятины", "REPLACED" => "Заменено", "Burned Hole" => "Прожженая дыра", "Scratch Light" => "Легкая царапина", "Prev Repair" => "Прошлый ремонт", "Ovrall Picture" => "Фото", "Scratched" => "Поцарапано", "Heavy Wear" => "Сильный износ", "After Market" => "Не оригинал", "Blows Cold" => "Дует холод", "Burn Hole" => "Прожженная дыра", "Vsbl Close Insp" => "Заметно", "Body Damage" => "Повреждение", "Body Dmg" => "Повреждение", "Mult Scratches" => "Множественные царапины", "Misaligned" => "Смещение", "Broken" => "Сломанный", "Dent/Paint Dmg" => "Вмятина/повреждение краски", "Replaced" => "Заменено", "Cracked" => "Трещина", "Scratch Heavy" => "Глубокая царапина", "Carpet" => "Коврик", "Rust" => "Ржавчина", "Missing" => "Отсутствует", "Gouged" => "Вогнуто", "Multiple Dents" => "Множественные вмятины", "Surface Damage" => "Повреждение поверхности", "INOP" => "Не работает", "Unknown" => "Неизвестно", "Mismatched" => "Не подходит", "Paint Dmg" => "Повреждение краски", "Poor" => "Плох.", "Unattached" => "Не подходит", "Repair" => "Ремонт", "OVER" => "Более", "Repainted" => "Перекрашено", "Torn" => "Порвано", "Squeak" => "Стук в подвеске", "Both" => "Оба", "Blows Warm" => "Дует горячий воздух", "Loose" => "Потеряно", "Scuffed" => "Процарапано", "Cut" => "Порезано", "Noise" => "Звук", "Leak" => "Течь", "Star in Glass" => "Звездочка из трещин на стекле", "Severe Damage" => "Серьезное повреждение", "Acceptable" => "Приемлемо", "Faded" => "Тусклая", "Mltpl inst" => "Много", "Flat" => "Колесо спущено", "Slight Wear" => "Легкий износ", "Scraped" => "Стерто", "Deployed" => "Сработавшие аэрбэги", "Frame Dmg" => "Повреждение рамы", "Factory" => "Заводское", "Hail Dmg Light" => "Повреждение от легкого града", "Good" => "Хорошее", "Hole" => "Дыра", "Scratch" => "Царапина", "Repair" => "Ремонт", "Bent" => "Согнуто", "Dent" => "Вмятина", "Ding" => "Маленькая вмятина", "Chipped" => "Сколы", "Worn" => "Изношенный", "Pitted" => "Шероховатости", "Empty" => "Пусто", "Yes" => "Да", "No " => "Нет", "Empty" => "Пусто", "Dirty" => "Грязный", "Damages" => "Повреждения", "Cloth" => "Ткань", "Average" => "Среднее", "Collision Dmg" => "Повреждение от столкновения", "None" => "ничего" , "Permanent" => "постоянно" );
$lang['report']['damages']['condition']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^Factory #", "replace" => "Заводское " );
$lang['report']['damages']['condition']['dynamic'] = $array;
$array = array( "Mltpl inst" => "Много", "Vsbl Close Insp" => "Заметно", "Acceptable" => "Приемлемо", "unknown" => "Неизвестно", "Substd Repair" => "Не очень качественный ремонт", "Body Damage" => "Повреждение", "Surface Damage" => "Повреждение поверхности", "None" => "Нет" );
$lang['report']['damages']['sev']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^\\s*Less #", "replace" => "Меньше " );
$array[] = array( "pattern" => "#^\\s*Mltpl inst #", "replace" => "Много " );
$array[] = array( "pattern" => "#^\\s*GR #", "replace" => "Более " );
$array[] = array( "pattern" => "#^\\s*(\\d+)&\\#034; to (\\d+)&\\#034;#", "replace" => "От \\1&#034; до \\2&#034;" );
3 & ( $lang['report']['damages']['sev']['dynamic'] = $array );
$array = array( "GRY" => "Серый", "SILVER" => "Серебро", "SLV" => "Серебро", "MAROON" => "Темно-красный", "BLACK" => "Черный", "BLUE" => "Синий", "BLU" => "Синий", "GOLD" => "Золотой", "BEI" => "Бежевый", "BEIGE" => "Бежевый", "CHAMP" => "Шампань", "BRN" => "Коричневый", "TAN" => "Бежевый", "GRAY" => "Серый", "GREY" => "Серый", "GREEN" => "Зеленый", "WHITE" => "Белый", "RED" => "Красный", "BLK" => "Черный", "BROWN" => "Коричневый", "OLIVE" => "Оливковый" );
$lang['report']['colors'] = $array;
$array = array( "5.0, Extra Clean" => "5 баллов, очень чисто", "5.0, Perfect" => "5 баллов, отличное", "Grade 5, Clean" => "5 баллов, чисто", "Grade 4, Clean" => "4 балла, чисто", "3.0, Average" => "3 балла, средне", "Grade 2, Rough" => "2 балла, посредственное", "Grade 1, Extra Rough" => "1 балл, очень посредственное" );
$lang['report']['general_information']['Condition/Grade'] = $array;
$lang['report']['general_information']['Ext Color/Code'] = $lang['report']['colors'];
$lang['report']['general_information']['Int Color/Code'] = $lang['report']['colors'];
$lang['report']['general_information']['Certified'] = $lang['yes_no'];
$lang['report']['general_information']['Drivable'] = $lang['yes_no'];
$lang['report']['general_information']['Cyberlot'] = $lang['yes_no'];
$array = array( "VIN" => "VIN", "Body Style" => "Тип кузова", "Ext Color/Code" => "Цвет кузова", "Int Color/Code" => "Цвет салона", "Seller" => "Продавец", "Title State" => "Штат", "Certified" => "Сертификат", "Condition/Grade" => "Состояние", "Sale" => "Номер продажи", "Lane" => "Номер линии", "Run" => "Номер в очереди", "Inspection" => "Осмотр", "Drivable" => "На ходу", "Rcv Date" => "Дата поступления", "Mileage" => "Пробег, миль", "Factory Category" => "Категория", "Cyberlot" => "Киберлот" );
$lang['report']['general_information']['categories'] = $array;
$array = array( "ALL" => "Все" );
$lang['main']['all'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^(?:(\\d+)\\s+Days|)\\s*(?:(\\d+)\\s+Hours|)\\s*(?:(\\d+)\\s+Minutes|)#e", "replace" => "translate_time_left('\\1', '\\2', '\\3')" );
$lang['show']['time_left']['dynamic'] = $array;
$array = array( );
$array['Year'] = "Год";
$array['Make'] = "Марка";
$array['Model'] = "Модель";
$array['Trim'] = "Модификация";
$array['Mileage'] = "Пробег";
$array['Ext'] = "Цвет";
$array['Int'] = "Покрытие салона";
$array['MMR'] = "Прогнозируемая цена";
$array['Inventory'] = "Продавец";
$array['Sale Location'] = "Площадка";
$array['Lane | Run'] = "Номер линии и очереди";
$array['Seller'] = "Продавец";
$array['Sale Date | Time'] = "Дата продажи и время";
$lang['list']['sort'] = $array;
$array = array( );
$array['Passenger Vehicles'] = "Пассажирский транспорт";
$array['- Car'] =   " - легковые";
$array['- Truck'] = " - грузовики";
$array['- SUV'] = " - спортивные внедорожники";
$array['- Van'] = " - вэны";
$array['Recreational'] = "Фургоны";
$array['Boats'] = "Лодки";
$array['Boat'] = "Лодка";
$array['Motorcycle'] = "Мотоциклы";
$array['Power Sports'] = "Спортивные";
$array['PowerSports'] = "Спортивные";
$array['Heavy Trucks'] = "Грузовые";
$array['Heavy Truck'] = "Грузовые";
$array['Salvage'] = "Аварийные";
$array['Other'] = "Другое";
$lang['vehicleTypeNav'] = $array;
$array = array( );
$array['Odometer'] = "Пробег";
$array['Interior Color'] = "Цвет салона";
$array['MMR Value'] = "Прогнозизуемая цена";
$array['Engine Type'] = "Тип двигателя";
$array['Exterior Color'] = "Цвет кузова";
$array['Condition Grade'] = "Состояние";
$array['Transmission'] = "Трансмиссия";
$array['Top Type'] = "Тип крыши";
$array['Drive Train'] = "Привод";
$array['Interior Type'] = "Покрытие салона";
$lang['advancedLinks'] = $array;
$array = array( );
$array[] = array( "pattern" => "#([$\\d,]+) to ([$\\d,]+)#", "replace" => "От \\1 до \\2" );
$array[] = array( "pattern" => "#([$\\d,]+) and higher#", "replace" => "От \\1 и больше" );
$lang['Advanced Fields']['Odometer']['dynamic'] = $array;
$array = array( );
$array['Beige'] = "Бежевый";
$array['Black'] = "Черный";
$array['Blue'] = "Синий";
$array['Brown'] = "Коричневый";
$array['Burgundy'] = "Темно-красный";
$array['Charcoal'] = "Темно-серый";
$array['Copper'] = "Медно-красный";
$array['Gold'] = "Золото";
$array['Gray'] = "Серый";
$array['Green'] = "Зеленый";
$array['Off White'] = "Оттенки белого";
$array['Orange'] = "Оранжевый";
$array['Purple'] = "Фиолетовый";
$array['Red'] = "Красный";
$array['Silver'] = "Серебристый";
$array['Tan'] = "Бежевый";
$array['White'] = "Белый";
$array['Yellow'] = "Желтый";
$array['Not Available'] = "Нет данных";
$array['Other'] = "Другой";
$array['Champagne'] = "Брызги шампанского";
$array['Cream'] = "Кремовый";
$array['Dark Green'] = "Темно-зеленый";
$array['Grey'] = "Серый";
$array['Light Green'] = "Светло-зеленый";
$array['Multi-Color'] = "Многоцветный";
$array['Offwhite'] = "Не совсем белый";
$array['Pink'] = "Розовый";
$array['Turquoise'] = "Бирюзовый";
$lang['Advanced Fields']['Interior Color']['static'] = $array;
$array = array( );
$array[] = array( "pattern" => "#(\\d+) Cyl. Gasoline Turbo#", "replace" => "\\1 цил. турбо бензин" );
$array[] = array( "pattern" => "#(\\d+) Cyl. Gasoline#", "replace" => "\\1 цил. бензин" );
$array[] = array( "pattern" => "#(\\d+) Cyl. Diesel Turbo#", "replace" => "\\1 цил. турбо-дизель" );
$array[] = array( "pattern" => "#(\\d+) Cyl. Diesel#", "replace" => "\\1 цил. дизель" );
$array[] = array( "pattern" => "#(\\d+) Cyl. Ethanol#", "replace" => "\\1 цил. этинол" );
$array[] = array( "pattern" => "#(\\d+) Cyl. Hybrid#", "replace" => "\\1 цил. гибрид" );
$array[] = array( "pattern" => "#(\\d+) Cyl. Gasoline#", "replace" => "\\1 цил. бензин" );
$lang['Advanced Fields']['Engine Type']['dynamic'] = $array;
$array = array( );
$array['ALL'] = "Все";
$array['Rotary'] = "Роторный";
$array['Electric'] = "Электродвигатель";
$lang['Advanced Fields']['Engine Type']['static'] = $array;
$array = array( "0 - Salvage" => "0 - Аварийное", "1 - Extra Rough" => "1 - Плохое", "2 - Rough" => "2 - Посредственное", "3 - Average" => "3 - Средне", "4 - Clean" => "4 - Чисто", "5 - Extra Clean" => "5  - Очень чисто" );
$lang['Advanced Fields']['Condition Grade']['static'] = $array;
$array = array( "Automatic" => "Автоматическая", "Manual" => "Механическая" );
$lang['Advanced Fields']['Transmission']['static'] = $array;
$array = array( );
$array['Convertible Top'] = "Откидной верх";
$array['Hard Top Roof'] = "Жесткая крыша";
$array['Moon Roof'] = "Прозрачный люк";
$array['Sun Roof'] = "Обычный люк";
$array['T-Top Roof'] = "T-образная";
$array['Tilt Slide Roof'] = "Панарамный люк";
$array['Vinyl Top Roof'] = "Виниловый верх";
$lang['Advanced Fields']['Top Type']['static'] = $array;
$array = array( );
$array['Convertible Top'] = "Откидной верх";
$array['Hard Top'] = "Жесткая крыша";
$array['Moon'] = "Прозрачный люк";
$array['Sun'] = "Обычный люк";
$array['T-Top'] = "T-образная";
$array['Tilt Slide'] = "Панарамный люк";
$array['Vinyl Top'] = "Виниловый верх";
$lang['roof_type'] = $array;
$array = array( "Not Available" => "Нет данных", "2 Wheel Drive" => "2 колеса", "4 Wheel Drive" => "Привод на 4 колеса", "All Wheel Drive" => "Привод на все колёса" );
$lang['Advanced Fields']['Drive Train']['static'] = $array;
$array = array( );
$array['Cloth'] = "Ткань";
$array['Leather'] = "Кожа";
$array['Vinyl'] = "Пластик";
$lang['Advanced Fields']['Interior Type']['static'] = $array;
$array = array( );
$array['Any Inventory'] = "Любой аукцион";
$array['Auction Pre-Sales'] = "Предварительный";
$array['OVE.com'] = "Фиксированные цены";
$array['Simulcast'] = "Аукцион";
$lang['inventory'] = $array;
$array = array( );
$array[] = array( "pattern" => "#^Select Sort#", "replace" => "Выберите сортировку" );
$array[] = array( "pattern" => "#^Year#", "replace" => "Год" );
$array[] = array( "pattern" => "#^Make#", "replace" => "Марка" );
$array[] = array( "pattern" => "#^Model#", "replace" => "Модель" );
$array[] = array( "pattern" => "#^Trim#", "replace" => "Модификация" );
$array[] = array( "pattern" => "#^Odometer#", "replace" => "Пробег" );
$array[] = array( "pattern" => "#^Ext#", "replace" => "Цвет кузова" );
$array[] = array( "pattern" => "#^Int#", "replace" => "Цвет салона" );
$array[] = array( "pattern" => "#^MMR#", "replace" => "Прогнозируемая цена" );
$array[] = array( "pattern" => "#^Inventory#", "replace" => "Тип аукциона" );
$array[] = array( "pattern" => "#^Sale Location#", "replace" => "Площадка" );
$array[] = array( "pattern" => "#^Lane \\| Run#", "replace" => "Номер линии | Номер в очерени" );
$array[] = array( "pattern" => "#^Seller#", "replace" => "Продавец" );
$array[] = array( "pattern" => "#^Sale Date \\| Time#", "replace" => "Дата продажи | Время" );
$array[] = array( "pattern" => "#Grade#", "replace" => "Состояние" );
$array[] = array( "pattern" => "#Location#", "replace" => "Площадка" );
$array[] = array( "pattern" => "#Date / Time#", "replace" => "Дата / время" );
$array[] = array( "pattern" => "#Lane / Run#", "replace" => "Номер линии / номер в очереди" );
$lang['list']['select_sort']['dynamic'] = $array;
$array = array( );
$array[] = array( "pattern" => "#\\s+mi#", "replace" => " миль" );
$array[] = array( "pattern" => "#\\s+km#", "replace" => " км." );
$lang['list']['Odometer']['dynamic'] = $array;
$array = array( );
$array['Not Available'] = "Нет данных";
$array['Dual'] = "Две";
$array['Side'] = "Сторона";
$lang['Airbags'] = $array;
$array = array( );
$array['Current Bid'] = "Текущая цена";
$array['Buy Now'] = "Купить сейчас";
$array['Time Left'] = "Время до окончания";
$array['Start Date'] = "Дата начала";
$array['End Date'] = "Дата окончания";
$array['Facilitated'] = "Размещен";
$array['Facilitating Location'] = "Площадка";
$lang['show']['Sale Status'] = $array;
$array = array( );
$array['Seller'] = "Продавец";
$array['Lane #'] = "Линия";
$array['Run #'] = "Очередь";
$array['Location'] = "Площадка";
$array['Sale Date'] = "Дата продажи";
$array['Sale Time'] = "Время продажи";
$lang['show']['Sale Information'] = $array;
#--------------------damage_array for condition report------------------------

$search = array ();
$replace = array ();
$search[] = 'class="header14bold">DAMAGES</td>';$replace[] = '><b>Повреждения</b></td>';
$search[] = '>DESCRIPTION</td>';$replace[] = '><b>Описание</b></td>';
$search[] = '>CONDITION</td>';$replace[] = '><b>Состояние</b></td>';
$search[] = '>SEVERITY</td>';$replace[] = '><b>Степень</b></td>';
$search[] = '>REPAIR<br>HOURS</td>';$replace[] = '><b>Ремонт</b></td>';
$search[] = '>PAINT<br>HOURS</td>';$replace[] = '><b>Покраска</b></td>';
$search[] = '>PART<br>HOURS</td>';$replace[] = '><b>Запчасти</b></td>';
$search[] = '>TOTAL<br>HOURS</td>';$replace[] = '><b>Всего</b></td>';
$search[] = '>TOTALS</td>';$replace[] = '><b>ИТОГО</b></td>';
$search[] = 'class="data12"';$replace[] = '';
$search[] = 'class="header12bold"';$replace[] = '';
//----
$search[] = 'Repair Required';$replace[] = 'Требуется ремонт';
$search[] = 'Overall Picture';$replace[] = 'Общее фото';
$search[] = 'Windshield';$replace[] = 'Лобовое стекло';
$search[] = 'Overall Vehicle';$replace[] = 'Вся машина';
$search[] = 'Ovrall Picture';$replace[] = 'Общее фото';
$search[] = 'Fender';$replace[] = 'Крыло';
$search[] = 'Replacement Req';$replace[] = 'Требуется замена';
$search[] = 'Door';$replace[] = 'Дверь';
$search[] = 'Picture #';$replace[] = 'Фото #';
$search[] = 'Bumper Cover';$replace[] = 'Покрытие бампера';
$search[] = 'Missing';$replace[] = 'Потерян';
$search[] = 'Prev Repair';$replace[] = 'Прошлый ремонт';
$search[] = 'PREVIOUS REPAIR';$replace[] = 'ПРОШЛЫЙ РЕМОНТ';
$search[] = 'Rear Bumper Cov';$replace[] = 'Покрытие заднего бампера';
$search[] = 'Rear Bumper<';$replace[] = 'Задний бампер<';
$search[] = 'Acceptable';$replace[] = 'Приемлемо';
$search[] = '>Less ';$replace[] = '>Менее ';
$search[] = 'Scratched';$replace[] = 'Поцарапано';
$search[] = 'SCRATCHED';$replace[] = 'ПОЦАРАПАНО';
$search[] = 'Scratch Light';$replace[] = 'Легкая царапина';
$search[] = 'None';$replace[] = 'Отсуствует';
$search[] = 'Deck Lid';$replace[] = 'Deck Lid.';
$search[] = '1&#034; to 2&#034;';$replace[] = 'От 1&#034; до 2&#034;';
$search[] = '2&#034; to 3&#034;';$replace[] = 'От 2&#034; до 3&#034;';
$search[] = '3&#034; to 4&#034;';$replace[] = 'От 3&#034; до 4&#034;';
$search[] = '4&#034; to 5&#034;';$replace[] = 'От 4&#034; до 5&#034;';
$search[] = '5&#034; to 6&#034;';$replace[] = 'От 5&#034; до 6&#034;';
$search[] = '6&#034; to 7&#034;';$replace[] = 'От 6&#034; до 7&#034;';
$search[] = '7&#034; to 8&#034;';$replace[] = 'От 7&#034; до 8&#034;';
$search[] = '8&#034; to 9&#034;';$replace[] = 'От 8&#034; до 9&#034;';
$search[] = '9&#034; to 10&#034;';$replace[] = 'От 9&#034; до 10&#034;';
$search[] = '10&#034; to 11&#034;';$replace[] = 'От 10&#034; до 11&#034;';
$search[] = '11&#034; to 12&#034;';$replace[] = 'От 11&#034; до 12&#034;';
$search[] = 'L Qtr Panel';$replace[] = 'L Qtr Panel';
$search[] = 'R Qtr Panel';$replace[] = 'R Qtr Panel';
$search[] = 'CHIPPED';$replace[] = 'СКОЛЫ';
$search[] = '>Dent DENTED<';$replace[] = '>Вмятина<';
$search[] = 'Scratch Heavy';$replace[] = 'Глубокая царапина';
 $search[] = 'Inop';$replace[] = 'Не работает';
 $search[] = 'Multiple Chips';$replace[] = 'Множественные сколы';
 $search[] = 'Stained';$replace[] = 'Пятна';
 $search[] = 'Surface Damage';$replace[] = 'Повреждение поверхности';
 $search[] = 'Substd Repair';$replace[] = 'Не очень качественный ремонт';
 $search[] = 'Mult Scratches';$replace[] = 'Множественные царапины';
 $search[] = 'Scratches';$replace[] = 'Царапины';
 $search[] = 'On Car';$replace[] = 'В машине';
 $search[] = 'Edge';$replace[] = 'Сколы';
 $search[] = 'Light Damage';$replace[] = 'Легкое повреждение';
 $search[] = 'Peeling';$replace[] = 'Ободр.';
 $search[] = 'Burn';$replace[] = 'Прожженная';
 $search[] = 'Scratch';$replace[] = 'Царапина';
 $search[] = '>Dents';$replace[] = '>Вмятины';
 $search[] = 'Dent/No Paint Dmg';$replace[] = 'Вмятина/Не закрашенное повреждение';
 $search[] = 'Dings';$replace[] = 'Маленькие вмятины';
 $search[] = 'REPLACED';$replace[] = 'Заменено';
 $search[] = 'Burned Hole';$replace[] = 'Прожженая дыра';
 $search[] = 'Scratch Light';$replace[] = 'Легкая царапина';
 $search[] = 'Prev Repair';$replace[] = 'Прошлый ремонт';
 $search[] = 'Ovrall Picture';$replace[] = 'Фото';
 $search[] = 'Scratched';$replace[] = 'Поцарапано';
 $search[] = 'Heavy Wear';$replace[] = 'Сильный износ';
 $search[] = 'After Market';$replace[] = 'Не оригинал';
 $search[] = 'Blows Cold';$replace[] = 'Дует холод';
 $search[] = 'Burn Hole';$replace[] = 'Прожженная дыра';
 $search[] = 'Vsbl Close Insp';$replace[] = 'Заметно';
 $search[] = 'Body Damage';$replace[] = 'Повреждение';
 $search[] = 'Body Dmg';$replace[] = 'Повреждение';
 $search[] = 'Mult Scratches';$replace[] = 'Множественные царапины';
 $search[] = 'Misaligned';$replace[] = 'Смещение';
 $search[] = 'Broken';$replace[] = 'Сломанный';
 $search[] = 'Dent/Paint Dmg';$replace[] = 'Вмятина/повреждение краски';
 $search[] = 'Replaced';$replace[] = 'Заменено';
 $search[] = 'Cracked';$replace[] = 'Трещина';
 $search[] = 'Scratch Heavy';$replace[] = 'Глубокая царапина';
 $search[] = 'Carpet';$replace[] = 'Коврик';
 $search[] = 'Rust';$replace[] = 'Ржавчина';
 $search[] = 'Missing';$replace[] = 'Отсутствует';
 $search[] = 'Gouged';$replace[] = 'Вогнуто';
 $search[] = 'Multiple Dents';$replace[] = 'Множественные вмятины';
 $search[] = 'Surface Damage';$replace[] = 'Повреждение поверхности';
 $search[] = 'INOP';$replace[] = 'Не работает';
 $search[] = 'Unknown';$replace[] = 'Неизвестно';
 $search[] = 'Mismatched';$replace[] = 'Не подходит';
 $search[] = 'Paint Dmg';$replace[] = 'Повреждение краски';
 $search[] = 'Poor';$replace[] = 'Плох.';
 $search[] = 'Unattached';$replace[] = 'Не подходит';
 $search[] = 'Repair';$replace[] = 'Ремонт';
 $search[] = 'OVER';$replace[] = 'Более';
 $search[] = 'Repainted';$replace[] = 'Перекрашено';
 $search[] = 'Torn';$replace[] = 'Порвано';
 $search[] = 'Squeak';$replace[] = 'Стук в подвеске';
 $search[] = 'Both';$replace[] = 'Оба';
 $search[] = 'Blows Warm';$replace[] = 'Дует горячий воздух';
 $search[] = 'Loose';$replace[] = 'Потеряно';
 $search[] = 'Scuffed';$replace[] = 'Процарапано';
 $search[] = 'Cut';$replace[] = 'Порезано';
 $search[] = 'Noise';$replace[] = 'Звук';
 $search[] = 'Leak';$replace[] = 'Течь';
 $search[] = 'Star in Glass';$replace[] = 'Звездочка из трещин на стекле';
 $search[] = 'Severe Damage';$replace[] = 'Серьезное повреждение';
 $search[] = 'Acceptable';$replace[] = 'Приемлемо';
 $search[] = 'Faded';$replace[] = 'Тусклая';
 $search[] = 'Mltpl inst';$replace[] = 'Много';
 $search[] = 'Flat';$replace[] = 'Колесо спущено';
 $search[] = 'Slight Wear';$replace[] = 'Легкий износ';
 $search[] = 'Scraped';$replace[] = 'Стерто';
 $search[] = 'Deployed';$replace[] = 'Сработавшие аэрбэги';
 $search[] = 'Frame Dmg';$replace[] = 'Повреждение рамы';
 $search[] = 'Factory';$replace[] = 'Заводское';
 $search[] = 'Hail Dmg Light';$replace[] = 'Повреждение от легкого града';
 $search[] = 'Good';$replace[] = 'Хорошее';
 $search[] = 'Hole';$replace[] = 'Дыра';
 $search[] = 'Scratch';$replace[] = 'Царапина';
 $search[] = 'Repair';$replace[] = 'Ремонт';
 $search[] = 'Bent';$replace[] = 'Согнуто';
 $search[] = 'Dent';$replace[] = 'Вмятина';
 $search[] = 'Ding';$replace[] = 'Маленькая вмятина';
 $search[] = 'Chipped';$replace[] = 'Сколы';
 $search[] = 'Worn';$replace[] = 'Изношенный';
 $search[] = 'Pitted';$replace[] = 'Шероховатости';
 $search[] = 'Empty';$replace[] = 'Пусто';
 $search[] = 'Yes';$replace[] = 'Да';
 $search[] = 'No ';$replace[] = 'Нет';
 $search[] = 'Empty';$replace[] = 'Пусто';
 $search[] = 'Dirty';$replace[] = 'Грязный';
 $search[] = 'Damages';$replace[] = 'Повреждения';
 $search[] = 'Cloth';$replace[] = 'Ткань';
 $search[] = 'Average';$replace[] = 'Среднее';
 $search[] = 'Collision Dmg';$replace[] = 'Повреждение от столкновения';
 $search[] = 'Permanent';$replace[] = 'постоянно';
$search[] = 'Cruise Control';$replace[] = 'Круиз-контроль';
$search[] = 'Pin Stripe';$replace[] = '!!_Pin Stripe';
$search[] = 'Inside Bed';$replace[] = 'Кровать внутри';
$search[] = 'Interior';$replace[] = 'Салон';
$search[] = 'Needs Cleaning';$replace[] = 'Нуждается в очистке';
$search[] = 'Power Steering';$replace[] = '!!_Power Steering';
$search[] = '>Hood<';$replace[] = '>Капот<';
$search[] = '>Front Bumper<';$replace[] = '>Передний бампер<';
$search[] = '>REPAIRED</td>';$replace[] = '>Восстановлено</td>';
$search[] = '>Roof<';$replace[] = '>Крыша<';
$search[] = '>Rear<';$replace[] = '>Задняя часть<';
$search[] = 'Right Side';$replace[] = 'Правая сторона';
$search[] = 'Accessories';$replace[] = 'Аксессуары';
$search[] = 'Oxidized';$replace[] = 'Окислено';
$search[] = 'Unacceptable';$replace[] = 'Неприемлемо';
$search[] = '>Grille<';$replace[] = '>Решетка<';
$search[] = '>Rear';$replace[] = '>Заднее';
//$search[] = '';$replace[] = '';
$searchDMG = $search;
$replaceDMG = $replace;
#--------------------/damage_array for condition report------------------------
$search = array ();
$replace = array ();



$array = array( );
$array['ac'] = '4294942350';
$array['acura'] = '4294960945';
$array['alfa_romeo'] = '4294960898';
$array['am_general'] = '4294960936';
$array['american'] = '4294943877';
$array['aston_martin'] = '4294960917';
$array['asuna'] = '4294937063';
$array['audi'] = '4294960949';
$array['avanti_ii'] = '4294943876';
$array['bentley'] = '4294960937';
$array['bertone'] = '4294943875';
$array['bmw'] = '4294960970';
$array['bugatti'] = '4294942358';
$array['buick'] = '4294960962';
$array['cadillac'] = '4294960963';
$array['checker'] = '4294937005';
$array['chevrolet'] = '4294960967';
$array['chrysler'] = '4294960956';
$array['citroen'] = '4294942333';
$array['cross_lander'] = '4294937026';
$array['daewoo'] = '4294960922';
$array['daihatsu'] = '4294943874';
$array['datsun'] = '4294960914';
$array['delorean'] = '4294943931';
$array['dodge'] = '4294960943';
$array['eagle'] = '4294960913';
$array['excalibur'] = '4294943903';
$array['ferrari'] = '4294960911';
$array['fiat'] = '4294943902';
$array['ford'] = '4294960948';
$array['freightliner'] = '4294960900';
$array['gem'] = '4294943901';
$array['geo'] = '4294960925';
$array['gmc'] = '4294960966';
$array['greatdane'] = '4294960916';
$array['hino'] = '4294942415';
$array['honda'] = '4294960968';
$array['hummer'] = '4294960950';
$array['hyundai'] = '4294960931';
$array['infiniti'] = '4294960952';
$array['international'] = '4294960926';
$array['isuzu'] = '4294960930';
$array['iveco'] = '4294937051';
$array['jaguar'] = '4294960942';
$array['jeep'] = '4294960969';
$array['kenworth'] = '4294960921';
$array['kia'] = '4294960933';
$array['lada'] = '4294937048';
$array['laforza'] = '4294943900';
$array['lamborghini'] = '4294952753';
$array['lancia'] = '4294937004';
$array['land_rover'] = '4294960947';
$array['lexus'] = '4294960951';
$array['lincoln'] = '4294960957';
$array['lotus'] = '4294960939';
$array['mack'] = '4294960915';
$array['maserati'] = '4294960946';
$array['maybach'] = '4294943899';
$array['mazda'] = '4294960932';
$array['mercedes-benz'] = '4294960954';
$array['mercury'] = '4294960944';
$array['merkur'] = '4294943898';
$array['mg'] = '4294942331';
$array['mini'] = '4294960955';
$array['mitsubishi'] = '4294960935';
$array['mitsubishi_fuso'] = '4294937046';
$array['morgan'] = '4294942332';
$array['nash'] = '4294942325';
$array['nissan'] = '4294960941';
$array['oldsmobile'] = '4294960929';
$array['oshkosh'] = '4294937049';
$array['panoz'] = '4294943897';
$array['passport'] = '4294937013';
$array['peterbilt'] = '4294960919';
$array['peugeot'] = '4294943907';
$array['plymouth'] = '4294960928';
$array['pontiac'] = '4294960965';
$array['porsche'] = '4294960960';
$array['qvale'] = '4294943906';
$array['renault'] = '4294937014';
$array['rolls-royce'] = '4294960986';
$array['saab'] = '4294960958';
$array['saleen'] = '4294942330';
$array['saturn'] = '4294960964';
$array['scion'] = '4294960927';
$array['smart'] = '4294942323';
$array['spyker'] = '4294942324';
$array['sterling'] = '4294943905';
$array['subaru'] = '4294960938';
$array['suzuki'] = '4294960934';
$array['thomas'] = '4294937023';
$array['toyota'] = '4294960953';
$array['triumph'] = '4294942262';
$array['tvr'] = '4294937030';
$array['vector'] = '4294943904';
$array['volkswagen'] = '4294960961';
$array['volvo'] = '4294960959';
$array['yugo'] = '4294937057';

$lang['convertmake'] = $array;




















?>
